# https://github.com/marketplace/actions/sphinx-build
name: CI_push

on:
  push:
    branches:
      - main
      
jobs:
  build:
    runs-on: ubuntu-latest
    container: siewyanhoh/sphinx-env:latest
    
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: build sphinx
        run: |
          cd docsrc
          make github
          
      - name: store artifact output website
        uses: actions/upload-artifact@v2
        with:
          name: build output file
          path: docs/
      - name: store artifact pdf
        uses: actions/upload-artifact@v2
        with:
          name: PDF documentation
          path: docsrc/_build/rinoh/cms-gen.pdf

      #- name: Generate coverage report
      #  run: |
      #    pip3.8 install pytest
      #    pip3.8 install pytest-cov
      #    pytest --cov=./ --cov-report=xml

      #- name: Upload coverage to Codecov
      #  uses: codecov/codecov-action@v1
      #  with:
      #    token: ${{ secrets.CODECOV_TOKEN }} # not required for public report
      #    file: ./coverage1.xml, ./coverage2.xml # optional
      #    #directory: ./coverage/reports/
      #    flags: unittests # optional
      #    name: codecov-umbrella
      #    fail_ci_if_error: true # optional (default = false)
      #    verbose: true # optional (default = false)
          
  # Publish built docs to gh-pages branch.
  autohost:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: deploys new changes
        run: git clone https://github.com/SiewYan/cmsgen.github.io.git --branch gh-pages --single-branch gh-pages
        
      - name: downloads output files
        uses: actions/download-artifact@v2
        with:
          name: build output file
          path: gh-pages/
             
      - name: commit new changes    
        run: |
          cd gh-pages
          git config --local user.email "siew.yan.hoh@github.com"
          git config --local user.name "SiewYan"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
           
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          
          
          
          
          
          
          
          
          
          
  
