name: Pull Request Docs Check

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    container: siewyanhoh/sphinx-env:latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        
      - name: build sphinx
        run: |
          cd docsrc
          make github
          
      - name: store artifact output website
        uses: actions/upload-artifact@v2
        with:
          name: build output file
          path: docs/
      - name: store artifact pdf
        uses: actions/upload-artifact@v2
        with:
          name: PDF documentation
          path: docsrc/_build/rinoh/cms-gen.pdf
